# Mongo-Sync Configurations

local:
  db: 'marketing'
  host:
    port: 27017
  access:
    username:
    password:
    authenticationDatabase:

remote:
  db: 'marketing'
  host:
    url: '173.230.137.242'
    port: 27017
  access:
    username:
    password:
    authenticationDatabase:

tunnel:
  on: false
  access:
    username: 'remote_ssh_user'
    port: 22

# For now :local just
# assumes DB is at localhost:port

# All of the parameters above are required,
# without them, the script will fail

# `authenticationDatabase` is optional